### ISSUE TITLE
你好，请问能加个qq吗，有些问题想问你

### ISSUE THREAD

**Issue by anli001024** [Topthinking/react-webapp-dianping#1]
我的qq：53218936，请问你能共享你react-模仿大众点评的视频给我吗。。。。穷学生了

**Comment by Topthinking** [comment]
你可以照着我的源码  和 文件目录结构去敲代码，主要还是要理解redux工作流

**Comment by anli001024** [comment]
源码和文件目录我都研究过了，想看视频是因为想了解整个项目的构架思想，希望您能共享给我，谢谢啦

**Comment by vdouw99** [comment]
楼主愿将代码分享，因为是属于他的；视频他没有版权。。
有些话说一遍就够了，别人不欠你什么。。
