### ISSUE TITLE
打包到gitpages上的接口请求返回数据问题

### ISSUE THREAD

**Issue by wuyanwen** [Topthinking/react-webapp-dianping#8]
http://topthinking.github.io/dianping/ 放到gitpages上面的这个页面按说不能请求接口返回的数据了，比如http://localhost:8080/api/homelist/%E4%B8%8A%E6%B5%B7/1，但为什么首页的猜你喜欢界面上还能有数据显示呢

**Comment by Topthinking** [comment]
这里的数据 我写在了文件里面  这里面做了一个http返回码的判断

**Comment by wuyanwen** [comment]
OK
